name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependency
      run: sudo update && sudo apt install libgit2-dev libarchive-dev libcurl4-gnutls-dev
    - name: make
      run: make
